# Full IRQ question set. Each question has an optional "weight" (relative
# importance within its section) and optional "risk_factor" (links to scoring).
# Section budgets live in excel_io.py (SECTION_WEIGHTS) and auto-redistribute
# when questions are added/removed.

QUESTIONS = [

    # ==========================================================
    # A - GENERAL INFORMATION
    # ==========================================================
    {"section": "A - General Information", "id": "A1a", "type": "number", "weight": 2,
     "risk_factor": "cust_high_risk_ratio",
     "question": "How many total customers (excluding closed) were in the Assessment Unit at the close of the assessment period?",
     "fields": ["Individual Customers", "Non-Individual Customers"]},
    {"section": "A - General Information", "id": "A1b", "type": "number", "weight": 1,
     "question": "How many active customers (excluding dormant) were in the Assessment Unit at the close of the assessment period?",
     "fields": ["Individual Customers", "Non-Individual Customers"]},
    {"section": "A - General Information", "id": "A1c", "type": "currency", "weight": 1,
     "question": "What was the total value of inward transactions (domestic and international) regardless of currency denomination, for the assessment period?",
     "fields": ["AED"]},
    {"section": "A - General Information", "id": "A1d", "type": "currency", "weight": 1,
     "question": "What was the total value of inward USD transactions for the assessment period?",
     "fields": ["AED"]},
    {"section": "A - General Information", "id": "A1e", "type": "currency", "weight": 1,
     "question": "What was the total value of domestic inward transactions for the assessment period?",
     "fields": ["AED"]},
    {"section": "A - General Information", "id": "A1f", "type": "currency", "weight": 1,
     "question": "What was the value of physical cash inward transactions processed over the counter and through ATMs/CDMs for the assessment period?",
     "fields": ["AED"]},
    {"section": "A - General Information", "id": "A1g", "type": "currency", "weight": 1,
     "question": "What was the total value of outward transactions (domestic and international) regardless of currency denomination, for the assessment period?",
     "fields": ["AED"]},
    {"section": "A - General Information", "id": "A1h", "type": "currency", "weight": 1,
     "question": "What was the total value of outward USD transactions for the assessment period?",
     "fields": ["AED"]},
    {"section": "A - General Information", "id": "A1i", "type": "currency", "weight": 1,
     "question": "What was the total value of domestic outward transactions for the assessment period?",
     "fields": ["AED"]},
    {"section": "A - General Information", "id": "A1j", "type": "currency", "weight": 1,
     "question": "What was the value of physical cash outward transactions processed over the counter and through ATMs/CDMs for the assessment period?",
     "fields": ["AED"]},
    {"section": "A - General Information", "id": "A1k", "type": "number", "weight": 1,
     "question": "What was the total volume (domestic and international) of inward transactions for the assessment period?",
     "fields": ["Volume"]},
    {"section": "A - General Information", "id": "A1l", "type": "number", "weight": 1,
     "question": "What was the total volume (domestic and international) of outward transactions for the assessment period?",
     "fields": ["Volume"]},
    {"section": "A - General Information", "id": "A1m", "type": "number", "weight": 1,
     "question": "What was the volume of physical cash inward transactions processed over the counter and through ATMs/CDMs for the assessment period?",
     "fields": ["Volume"]},
    {"section": "A - General Information", "id": "A1n", "type": "number", "weight": 1,
     "question": "What was the volume of physical cash outward transactions processed over the counter and through ATMs/CDMs for the assessment period?",
     "fields": ["Volume"]},
    {"section": "A - General Information", "id": "A1o", "type": "number", "weight": 1,
     "question": "What was the total volume of inward USD transactions for the assessment period?",
     "fields": ["Volume"]},
    {"section": "A - General Information", "id": "A1p", "type": "number", "weight": 1,
     "question": "What was the total volume of domestic inward transactions for the assessment period?",
     "fields": ["Volume"]},
    {"section": "A - General Information", "id": "A1q", "type": "number", "weight": 1,
     "question": "What was the total volume of outward USD transactions for the assessment period?",
     "fields": ["Volume"]},
    {"section": "A - General Information", "id": "A1r", "type": "number", "weight": 1,
     "question": "What was the total volume of domestic outward transactions for the assessment period?",
     "fields": ["Volume"]},
    {"section": "A - General Information", "id": "A2a", "type": "textarea", "weight": 1,
     "question": "Please describe any other aspects that require further explanation.",
     "fields": ["Comments"]},
    {"section": "A - General Information", "id": "A2b", "type": "textarea", "weight": 1,
     "question": "Describe the level of impact of ongoing and proposed/pending projects (including remediation, elimination of backlogs, etc.) involving AML/CTF, TFS-TF, PF and ABC compliance on the Financial Crime Compliance Program.",
     "fields": ["Impact Description"]},

    # ==========================================================
    # B - GEOGRAPHY
    # ==========================================================
    {"section": "B - Geography", "id": "B1a", "type": "boolean", "weight": 3,
     "risk_factor": "geo_sanctioned_dealings",
     "question": "Does the assessment unit facilitate/deal/transact with Individuals/Non-Individuals listed in any of the Applicable Sanctions Lists as per the Sanctions Policy?",
     "fields": ["Answer"]},
    {"section": "B - Geography", "id": "B1a_value", "type": "currency", "weight": 1,
     "question": "If yes to B1a, what was the value of these inward and outward transactions for the assessment period?",
     "fields": ["Inward Value (AED)", "Outward Value (AED)"]},
    {"section": "B - Geography", "id": "B1b", "type": "boolean", "weight": 2,
     "question": "Does the Assessment Unit process any transactions with Individuals/Non-Individuals listed on country-specific blacklist issued by the local regulator(s)?",
     "fields": ["Answer"]},
    {"section": "B - Geography", "id": "B1c", "type": "boolean", "weight": 2,
     "question": "Does the Assessment Unit process any transactions with Individuals/Non-Individuals listed in the Bank's Internal Blacklist?",
     "fields": ["Answer"]},
    {"section": "B - Geography", "id": "B1d", "type": "currency", "weight": 2,
     "question": "Value of inward transactions processed out of sanctioned countries during the assessment period.",
     "fields": ["Cuba", "Iran", "North Korea", "Sudan", "Ukraine (occupied regions)", "Myanmar"]},
    {"section": "B - Geography", "id": "B1e", "type": "currency", "weight": 2,
     "question": "Value of outward transactions processed to sanctioned countries during the assessment period.",
     "fields": ["Cuba", "Iran", "North Korea", "Sudan", "Ukraine (occupied regions)", "Myanmar"]},
    {"section": "B - Geography", "id": "B1f", "type": "percentage", "weight": 3,
     "risk_factor": "geo_high_risk_exposure",
     "question": "What was the % of inward transactions from countries with the below risk rating for the assessment period?",
     "fields": ["High %", "Medium %", "Low %", "Unrated %"]},
    {"section": "B - Geography", "id": "B1g", "type": "percentage", "weight": 3,
     "risk_factor": "geo_high_risk_exposure",
     "question": "What was the % of outward transactions to countries with the below risk rating for the assessment period?",
     "fields": ["High %", "Medium %", "Low %", "Unrated %"]},
    {"section": "B - Geography", "id": "B1i", "type": "currency", "weight": 1,
     "question": "Value of inward transactions received from high-risk countries listed in the Corruption Perception Index (CPI) for the assessment period.",
     "fields": ["AED"]},
    {"section": "B - Geography", "id": "B1j", "type": "currency", "weight": 1,
     "question": "Value of inward transactions received from high-risk jurisdictions (tax transparency risk) for the assessment period.",
     "fields": ["AED"]},
    {"section": "B - Geography", "id": "B1k", "type": "currency", "weight": 1,
     "question": "Value of outward transactions made to high-risk countries listed in the Corruption Perception Index (CPI) for the assessment period.",
     "fields": ["AED"]},
    {"section": "B - Geography", "id": "B1l", "type": "currency", "weight": 1,
     "question": "Value of outward transactions made to high-risk jurisdictions (tax transparency risk) for the assessment period.",
     "fields": ["AED"]},
    {"section": "B - Geography", "id": "B1p", "type": "boolean", "weight": 1,
     "question": "Was there an increase in transactions with high risk countries compared to previous assessment period?",
     "fields": ["Answer"]},
    {"section": "B - Geography", "id": "B2b", "type": "percentage", "weight": 2,
     "question": "What was the % of customers (Individual) that were residents of countries with the below risk rating for the assessment period?",
     "fields": ["High %", "Medium %", "Low %", "Unrated %"]},
    {"section": "B - Geography", "id": "B2c", "type": "percentage", "weight": 1,
     "question": "What was the distribution of customers (Individuals) that were residents or non-residents of UAE for the assessment period?",
     "fields": ["Resident in UAE %", "Non-resident in UAE %"]},
    {"section": "B - Geography", "id": "B2k", "type": "number", "weight": 1,
     "question": "How many customers (Individuals) were residents of high-risk countries listed in the CPI for the assessment period?",
     "fields": ["Customers"]},
    {"section": "B - Geography", "id": "B3b", "type": "percentage", "weight": 2,
     "question": "What was the % of customers (Individuals) that were nationals of countries with the below risk rating for the assessment period?",
     "fields": ["High %", "Medium %", "Low %", "Unrated %"]},
    {"section": "B - Geography", "id": "B4a", "type": "textarea", "weight": 1,
     "question": "Please identify the financial crime risk categories that were particularly prevalent in the jurisdiction (rationale to be provided).",
     "fields": ["Description"]},
    {"section": "B - Geography", "id": "B5a", "type": "textarea", "weight": 1,
     "question": "Please describe any other aspects that require further explanation in relation to the geographical exposure.",
     "fields": ["Comments"]},
    {"section": "B - Geography", "id": "B5b", "type": "textarea", "weight": 1,
     "question": "Describe the level of change undertaken or intended to the business strategy regarding countries in which it operates or transacts.",
     "fields": ["Comments"]},

    # ==========================================================
    # C - CUSTOMER TYPE
    # ==========================================================
    {"section": "C - Customer Type", "id": "C1g", "type": "boolean", "weight": 2,
     "question": "Did the Assessment Unit have any customers (Non-Individuals) whose beneficial owners were either unknown or indirectly held through nominee structures?",
     "fields": ["Answer"]},
    {"section": "C - Customer Type", "id": "C1i", "type": "boolean", "weight": 2,
     "question": "Did the Assessment Unit have Individuals or Non-Individuals that have been, or have beneficial owners that have been, convicted of financial crimes in any jurisdiction?",
     "fields": ["Answer"]},
    {"section": "C - Customer Type", "id": "C1j", "type": "boolean", "weight": 2,
     "question": "Did the Assessment Unit have a relationship with a correspondent bank that provides payable-through accounts or nested relationships?",
     "fields": ["Answer"]},
    {"section": "C - Customer Type", "id": "C2a", "type": "percentage", "weight": 2,
     "question": "What was the % of total customers operating in industries with the below risk rating for the assessment period?",
     "fields": ["High %", "Medium %", "Low %", "Unrated %"]},
    {"section": "C - Customer Type", "id": "C2f", "type": "percentage", "weight": 2,
     "question": "What was the % of total customers (Individuals) engaged in professions with the below risk rating for the assessment period?",
     "fields": ["High %", "Medium %", "Low %", "Unrated %"]},
    {"section": "C - Customer Type", "id": "C2e", "type": "boolean", "weight": 1,
     "question": "Did the Assessment Unit have any other nature of businesses that were categorised as unlicensed or prohibited?",
     "fields": ["Answer"]},
    {"section": "C - Customer Type", "id": "C3a", "type": "number", "weight": 3,
     "risk_factor": "cust_high_risk_ratio",
     "question": "What was the risk breakdown of all active customers (number of customers per risk rating)?",
     "fields": ["High Risk", "Medium Risk", "Low Risk", "Unrated"]},
    {"section": "C - Customer Type", "id": "C3b", "type": "number", "weight": 1,
     "question": "What were the total number of customers on-boarded during the assessment period?",
     "fields": ["Customers"]},
    {"section": "C - Customer Type", "id": "C3c", "type": "number", "weight": 1,
     "question": "Of the total customers on-boarded during the assessment period, how many were rated as 'high' risk?",
     "fields": ["Customers"]},
    {"section": "C - Customer Type", "id": "C3d", "type": "number", "weight": 1,
     "question": "Number of potential customers declined due to sanctions or proliferation financing risks during the assessment period.",
     "fields": ["Customers"]},
    {"section": "C - Customer Type", "id": "C3e", "type": "number", "weight": 1,
     "question": "Number of existing customer relationships exited or blocked due to sanctions or proliferation financing concerns during the assessment period.",
     "fields": ["Customers"]},
    {"section": "C - Customer Type", "id": "C4a", "type": "number", "weight": 3,
     "risk_factor": "cust_pep_exposure",
     "question": "Politically Exposed Persons (PEPs) - number of customers by category.",
     "fields": ["Domestic PEPs", "Foreign PEPs", "International Organization PEPs"]},
    {"section": "C - Customer Type", "id": "C4b", "type": "number", "weight": 1,
     "question": "High Net Worth Individuals (HNWI) and Family Offices - number of customers.",
     "fields": ["HNWI & Family Offices", "HNWI & Family Offices that are PEPs"]},
    {"section": "C - Customer Type", "id": "C4c", "type": "number", "weight": 2,
     "question": "Customers known to be subject to UN sanctions - number of customers.",
     "fields": ["Customers"]},
    {"section": "C - Customer Type", "id": "C4d", "type": "number", "weight": 2,
     "question": "Customers known to be subject to OFAC, EU or UK-HMT sanctions - number of customers.",
     "fields": ["Customers"]},
    {"section": "C - Customer Type", "id": "C4l", "type": "boolean", "weight": 1,
     "question": "Did the Assessment Unit have any customers on whose behalf a third party (e.g. lawyer/accountant) is authorized to act and transact?",
     "fields": ["Answer"]},
    {"section": "C - Customer Type", "id": "C4q", "type": "textarea", "weight": 1,
     "question": "Describe the level of change undertaken or intended to the client strategy, including targeting new client segments.",
     "fields": ["Comments"]},

    # ==========================================================
    # D - CHANNEL / INTERFACE
    # ==========================================================
    {"section": "D - Channel", "id": "D1a", "type": "number", "weight": 1,
     "question": "Number of customers onboarded through face-to-face channel without third-party introducers, intermediaries, agents or distributors.",
     "fields": ["Customers"]},
    {"section": "D - Channel", "id": "D1b", "type": "boolean", "weight": 3,
     "risk_factor": "chan_non_face_to_face",
     "question": "Were customers on-boarded through digital (non-face-to-face) channels or by intermediaries or third parties during the assessment period?",
     "fields": ["Answer"]},
    {"section": "D - Channel", "id": "D1c", "type": "number", "weight": 1,
     "question": "Total number of customers on-boarded through digital / intermediary / third-party channels (across portfolio).",
     "fields": ["Mobile Application", "Through Intermediaries", "Through Third Parties"]},
    {"section": "D - Channel", "id": "D1e", "type": "number", "weight": 2,
     "question": "Risk rating break-up of customers on-boarded through digital / intermediary / third-party channels.",
     "fields": ["High Risk", "Medium Risk", "Low Risk", "Unrated"]},
    {"section": "D - Channel", "id": "D2a", "type": "number", "weight": 1,
     "question": "Total volume of inward transactions processed through key channels.",
     "fields": ["Branches (Manual)", "Mobile App", "Online Banking", "ATM/CDM", "Business Online (Web)", "Business Online (H2H)"]},
    {"section": "D - Channel", "id": "D2b", "type": "currency", "weight": 1,
     "question": "Total value of inward transactions processed through key channels.",
     "fields": ["Branches (Manual)", "Mobile App", "Online Banking", "ATM/CDM", "Business Online (Web)", "Business Online (H2H)"]},
    {"section": "D - Channel", "id": "D2c", "type": "number", "weight": 1,
     "question": "Total number of customers serviced through key channels.",
     "fields": ["BPM", "Corporate Digital Onboarding", "Branches (Manual)", "Direct Sales (Manual)", "Third Party Sales Agent", "Mobile App", "Branch Digital Journey"]},

    # ==========================================================
    # E - PRODUCTS AND SERVICES
    # ==========================================================
    {"section": "E - Products", "id": "E1a", "type": "percentage", "weight": 3,
     "risk_factor": "prod_high_risk_ratio",
     "question": "What was the % of total customers availing products and services with the below risk rating for the assessment period?",
     "fields": ["High %", "Medium %", "Low %", "Unrated %"]},
    {"section": "E - Products", "id": "E1b", "type": "boolean", "weight": 1,
     "question": "Were any products/services provided through third party intermediaries (excluding affiliates)?",
     "fields": ["Answer"]},
    {"section": "E - Products", "id": "E1c", "type": "boolean", "weight": 1,
     "question": "Were any products/services offered to non-customers?",
     "fields": ["Answer"]},
    {"section": "E - Products", "id": "E1e", "type": "boolean", "weight": 1,
     "question": "Was there any product, service or delivery channel which was newly introduced by the Bank during the assessment period?",
     "fields": ["Answer"]},
    {"section": "E - Products", "id": "E1f", "type": "boolean", "weight": 1,
     "question": "If yes, was this offering considered innovative or uncommon in the UAE financial sector?",
     "fields": ["Answer"]},
    {"section": "E - Products", "id": "E1g", "type": "boolean", "weight": 1,
     "question": "Was the new product, service or delivery channel offered to customer types for whom it is traditionally uncommon or unexpected?",
     "fields": ["Answer"]},
    {"section": "E - Products", "id": "E1i", "type": "boolean", "weight": 1,
     "question": "Does the Assessment Unit offer safe deposit locker or hold mail accounts to customers?",
     "fields": ["Answer"]},
    {"section": "E - Products", "id": "E1k", "type": "number", "weight": 1,
     "question": "What is the total number of products and services offered by the Assessment Unit during the assessment period?",
     "fields": ["Number of Products"]},
    {"section": "E - Products", "id": "E1l", "type": "boolean", "weight": 1,
     "question": "Were all the products and services offered by the Assessment Unit approved by Compliance?",
     "fields": ["Answer"]},
    {"section": "E - Products", "id": "E1m", "type": "boolean", "weight": 2,
     "question": "Does the Assessment Unit offer products & services to customers categorised as VASPs?",
     "fields": ["Answer"]},
    {"section": "E - Products", "id": "E2a", "type": "textarea", "weight": 1,
     "question": "Please describe any other information associated with products and services.",
     "fields": ["Comments"]},
    {"section": "E - Products", "id": "E2b", "type": "textarea", "weight": 1,
     "question": "Describe the level of change undertaken or intended to the product strategy, including offering new products.",
     "fields": ["Comments"]},

    # ==========================================================
    # F - REGULATORY
    # ==========================================================
    {"section": "F - Regulatory", "id": "F1a", "type": "boolean", "weight": 1,
     "question": "Were there any prior regulatory enforcement actions related to AML/CTF, TFS-TF, PF and ABC compliance for the assessment period or the previous five years?",
     "fields": ["Answer"]},
    {"section": "F - Regulatory", "id": "F1c", "type": "boolean", "weight": 1,
     "question": "Were there any prior regulatory enforcement actions related to compliance with VASP regulations and guidelines for the assessment period or the previous five years?",
     "fields": ["Answer"]},
    {"section": "F - Regulatory", "id": "F2a", "type": "boolean", "weight": 1,
     "question": "Were there any outstanding regulatory issues related to AML/CTF, TFS-TF, PF and ABC from examinations for the assessment period or the previous five years?",
     "fields": ["Answer"]},
    {"section": "F - Regulatory", "id": "F2c", "type": "textarea", "weight": 1,
     "question": "Describe the level of financial crime concerns or increased focus expressed by CBUAE or regulators, related to markets, products, client segments, or geographies.",
     "fields": ["Comments"]},
    {"section": "F - Regulatory", "id": "F2d", "type": "boolean", "weight": 1,
     "question": "Were there any outstanding regulatory issues related to compliance with VASP regulations for the assessment period or the previous five years?",
     "fields": ["Answer"]},
    {"section": "F - Regulatory", "id": "F3a", "type": "boolean", "weight": 1,
     "question": "Were there any pending litigation related to AML/CTF, TFS-TF, PF and ABC for the assessment period or the previous five years?",
     "fields": ["Answer"]},
    {"section": "F - Regulatory", "id": "F3c", "type": "boolean", "weight": 1,
     "question": "Were there any pending litigation related to VASP regulations and guidelines for the assessment period or the previous five years?",
     "fields": ["Answer"]},
    {"section": "F - Regulatory", "id": "F4a", "type": "textarea", "weight": 1,
     "question": "Please describe any other aspects that require further explanation (Regulatory).",
     "fields": ["Comments"]},
    {"section": "F - Regulatory", "id": "F4b", "type": "textarea", "weight": 1,
     "question": "Describe the impact of latest results from the NRA/FATF mutual evaluation reports in the context of the Bank's commercial activities and risk profile.",
     "fields": ["Comments"]},

    # ==========================================================
    # G - STAFF AND THIRD PARTY
    # ==========================================================
    {"section": "G - Staff and Third Party", "id": "G1a", "type": "number", "weight": 1,
     "question": "Please indicate the total headcount of your Assessment Unit.",
     "fields": ["Headcount"]},
    {"section": "G - Staff and Third Party", "id": "G1b", "type": "number", "weight": 1,
     "question": "Please provide breakdown of FTE employed/working for your AU during the assessment period.",
     "fields": ["Permanent Staff", "Contractors / Fixed Term", "Outsourced FTE", "Interns"]},
    {"section": "G - Staff and Third Party", "id": "G1c", "type": "number", "weight": 1,
     "question": "Please indicate the total number of candidates hired during the assessment period.",
     "fields": ["Candidates"]},
    {"section": "G - Staff and Third Party", "id": "G1h", "type": "boolean", "weight": 1,
     "question": "Do you have employees/staff employed in countries other than the UAE?",
     "fields": ["Answer"]},
    {"section": "G - Staff and Third Party", "id": "G1i", "type": "boolean", "weight": 1,
     "question": "Have any of your employees received any Gifts & Entertainment during the assessment period?",
     "fields": ["Answer"]},
    {"section": "G - Staff and Third Party", "id": "G1k", "type": "boolean", "weight": 1,
     "question": "Does your Assessment Unit provide corporate sponsorship (e.g. sporting events, cultural events)?",
     "fields": ["Answer"]},
    {"section": "G - Staff and Third Party", "id": "G1l", "type": "boolean", "weight": 1,
     "question": "Does your Assessment Unit provide political contributions?",
     "fields": ["Answer"]},
    {"section": "G - Staff and Third Party", "id": "G1m", "type": "boolean", "weight": 1,
     "question": "Does your Assessment Unit provide charitable contributions?",
     "fields": ["Answer"]},
    {"section": "G - Staff and Third Party", "id": "G1n", "type": "number", "weight": 1,
     "question": "How many of your staff/employees during the assessment period were classified as Politically Exposed Persons (PEPs, including related parties)?",
     "fields": ["Employees"]},
    {"section": "G - Staff and Third Party", "id": "G2a", "type": "number", "weight": 1,
     "question": "Please indicate the number of third parties your Assessment Unit is working with (other than staff/employees).",
     "fields": ["Third Parties"]},
    {"section": "G - Staff and Third Party", "id": "G2b", "type": "number", "weight": 1,
     "question": "Please provide a breakdown of third parties into risk rating categories under Third Party Due Diligence.",
     "fields": ["High Risk", "Medium Risk", "Low Risk", "Unrated"]},
    {"section": "G - Staff and Third Party", "id": "G2k", "type": "boolean", "weight": 1,
     "question": "Do any of your third parties receive payments in cash?",
     "fields": ["Answer"]},
    {"section": "G - Staff and Third Party", "id": "G2n", "type": "boolean", "weight": 1,
     "question": "Can you contract parties without going through third party due diligence?",
     "fields": ["Answer"]},

    # ==========================================================
    # H - CYBER RISK
    # ==========================================================
    {"section": "H - Cyber Risk", "id": "H1a", "type": "number", "weight": 1,
     "question": "Number of cyber incidents that occurred during the assessment period for the Assessment Unit.",
     "fields": ["Ransomware", "Phishing", "Data Stolen by Fraudsters", "Unauthorised Access (Internal)", "Unauthorised Access (External)"]},
    {"section": "H - Cyber Risk", "id": "H1b", "type": "boolean", "weight": 1,
     "question": "Were critical financial crime compliance systems (e.g. sanctions screening, transaction monitoring) hosted on secure and segregated infrastructure?",
     "fields": ["Answer"]},
    {"section": "H - Cyber Risk", "id": "H1d", "type": "boolean", "weight": 1,
     "question": "Were APIs and interfaces with third-party tools (e.g. screening, case management) securely authenticated and monitored?",
     "fields": ["Answer"]},
    {"section": "H - Cyber Risk", "id": "H1e", "type": "boolean", "weight": 1,
     "question": "Has the institution experienced any cyber incident in the last 12 months affecting financial crime detection or reporting?",
     "fields": ["Answer"]},
    {"section": "H - Cyber Risk", "id": "H1f", "type": "boolean", "weight": 1,
     "question": "Was cybersecurity integrated into the design, testing, and deployment of financial crime systems?",
     "fields": ["Answer"]},
    {"section": "H - Cyber Risk", "id": "H1g", "type": "boolean", "weight": 1,
     "question": "Were the IT contractors or third parties engaged as subject matter experts potentially related to weapons of mass destruction or dual-use goods?",
     "fields": ["Answer"]},
    {"section": "H - Cyber Risk", "id": "H1h", "type": "boolean", "weight": 1,
     "question": "Were there any third-party contractors engaged to access sensitive materials or systems?",
     "fields": ["Answer"]},
]